version: '3.8'

services:
  hexagon-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/static:/usr/src/app/static
      - ./frontend/vite.config.ts:/usr/src/app/vite.config.ts
      - ./frontend/svelte.config.js:/usr/src/app/svelte.config.js
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # Equivalent to -i in docker run
    tty: true        # Equivalent to -t in docker run
  